---
# devopsenginar.vm_provisioner/tasks/check_and_install_vagrant.yml

- name: Include HashiCorp repository setup tasks
  ansible.builtin.include_tasks: _install_hashicorp_repo.yml
  when: ansible_os_family == "Debian" # Only run for Debian-based systems

- name: Check if Vagrant is installed
  ansible.builtin.command: vagrant --version
  register: vagrant_version_check
  changed_when: false
  failed_when: false
  check_mode: false # Don't run in check mode, always try to get version

- name: Get desired Vagrant version from provider default
  ansible.builtin.set_fact:
    vagrant_desired_version_major_minor: "{{ vm_provisioner_terraform_provider_version | regex_replace('^~>\\s*(\\d+\\.\\d+).*$', '\\1') }}"

- name: Determine if Vagrant needs installation or upgrade
  ansible.builtin.set_fact:
    install_vagrant: >-
      {{ vagrant_version_check.rc != 0 or
         (vagrant_version_check.stdout is defined and
          vagrant_version_check.stdout != '' and
          vagrant_version_check.stdout | regex_search('Vagrant\\s+(\\d+\\.\\d+)') and
          vagrant_version_check.stdout | regex_replace('Vagrant\\s+(\\d+\\.\\d+).*', '\\1') is version(vagrant_desired_version_major_minor, '<'))
      }}

- name: Install or upgrade Vagrant
  ansible.builtin.apt:
    name: vagrant
    state: present # Use 'latest' to ensure desired version if available, or 'present'
    update_cache: true
  when: ansible_os_family == "Debian" and install_vagrant